### ISSUE TITLE
color transform `color: #fff` to `text="[#fff]"`

### ISSUE THREAD

**Issue by zouhangwithsweet** [Simon-He95/transform-to-unocss-core#3]
Current:
![image](https://github.com/Simon-He95/transform-to-unocss-core/assets/21095710/f465eff0-63d0-4e0f-88d3-ec3edff60b2c)

Excepet:
`text-#fff` or `text-[#fff]`

**Comment by zouhangwithsweet** [comment]
and `bg="#5DA85E" border="[1px_solid_rgba(233,233,233,1)]"`. Is this expected logic?

**Comment by Simon-He95** [comment]
yes, toUnocss is for attr, used like `<div text="[#fff]" border="[1px_solid_rgba(233,233,233,1)]" />`.
I add toUnocssClass that used in class can be transformed to `text-#fff`
